# Generated by Django 3.2.16 on 2022-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../cld-sample-2.jpg', upload_to='images/'),
        ),
    ]
