# Generated by Django 3.2.16 on 2022-11-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
